/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.netology.pyas;

public class Main {

    public static void main(String[] args) {
        Box box = new Box();
        Player player = new Player(box);

        Thread boxThread = new Thread(box::run);
        Thread playerThread = new Thread(player::run);

        boxThread.start();
        playerThread.start();

        try {
            playerThread.join();
        } catch (InterruptedException e) {
        }
        boxThread.interrupt();
    }
}
